[package]
name = "librespot-core"
version = "0.1.0"
authors = ["Paul Lietar <paul@lietar.net>"]
build = "build.rs"

[dependencies.librespot-protocol]
path = "../protocol"

[dependencies]
base64 = "0.5.0"
byteorder = "1.0"
bytes = "0.4"
error-chain = { version = "0.11.0", default_features = false }
extprim = "1.5.1"
futures = "0.1.8"
httparse = "1.2.4"
hyper = "0.11.2"
hyper-proxy = { version = "0.4.1", default_features = false }
lazy_static = "0.2.0"
log = "0.3.5"
num-bigint = "0.1.35"
num-integer = "0.1.32"
num-traits = "0.1.36"
protobuf = "2.0.5"
rand = "0.6"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
shannon = "0.2.0"
tokio-codec = "0.1.1"
tokio-core = "0.1.2"
tokio-io = "0.1"
url = "1.7.0"
uuid = { version = "0.4", features = ["v4"] }
sha-1 = "0.8.0"
hmac = "0.7.0"
pbkdf2 = "0.3.0"
aes = "0.3.0"

[build-dependencies]
rand = "0.6"
vergen = "0.1.0"
